### ISSUE TITLE
LLMPredictor is deprecated

### ISSUE THREAD

**Issue by jpc-horizon** [AI-Bassem/moviebot#2]
I'm seeing this response 
LLMPredictor is deprecated, please use LLM instead.

thrown during 
`def create_service_context(llm_predictor, embeddings):
    """Create and return ServiceContext instance."""
    if "service_context" not in session:
        service_context = ServiceContext.from_defaults(
            llm_predictor=llm_predictor, chunk_size_limit=400, embed_model=embeddings
        )
        session["service_context"] = service_context
    return session["service_context"]`

**Comment by Bassem-Yacoube** [comment]
Thanks John. I updated the code to use FAISS instead of llama_index. The issue is resolved now
